export { ReactComponent as Happy } from './logo.svg';
export { ReactComponent as LandingIllustration } from './landing.svg';
export { ReactComponent as MapMarker } from './map-marker.svg';
export { ReactComponent as WhatsApp } from './whatsapp.svg';
export { ReactComponent as SuccessIllustration } from './success.svg';
export { ReactComponent as HappyVertical } from './logo-vertical.svg';
export { ReactComponent as Checked } from './checked.svg';
export { ReactComponent as AlertCircleNotification } from './alert-circle-notification.svg';
export { ReactComponent as NoOrphanagesIcon } from './no-orphanages.svg';
